# Generated by Django 5.1.3 on 2024-12-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_admin',
            new_name='tbl_adminreg',
        ),
    ]
