# Generated by Django 5.1.3 on 2024-12-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
