# Generated by Django 5.1.3 on 2024-12-28 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_stafftype_tbl_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('food_details', models.CharField(max_length=330)),
                ('food_price', models.CharField(max_length=30)),
                ('food_photo', models.FileField(upload_to='Assets/Files/Food')),
                ('food_status', models.CharField(max_length=30)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
    ]
