# Generated by Django 5.1.3 on 2024-12-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
                ('job_details', models.CharField(max_length=130)),
                ('job_status', models.CharField(max_length=40)),
                ('job_postdate', models.CharField(max_length=30)),
                ('job_validdate', models.CharField(max_length=30)),
            ],
        ),
    ]
