# Generated by Django 5.1.3 on 2024-12-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_job',
            name='job_postdate',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tbl_job',
            name='job_validdate',
            field=models.DateField(max_length=30),
        ),
    ]
