# Generated by Django 5.1.3 on 2025-01-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_tbl_job_job_postdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_job',
        ),
    ]
