# Generated by Django 5.1.3 on 2025-01-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_delete_tbl_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=30)),
                ('job_details', models.CharField(max_length=130)),
                ('job_status', models.CharField(max_length=40)),
                ('job_postdate', models.DateField(auto_now_add=True)),
                ('job_validdate', models.DateField(max_length=30)),
                ('job_hours', models.CharField(max_length=30)),
                ('job_salary', models.CharField(max_length=30)),
            ],
        ),
    ]
