# Generated by Django 5.1.3 on 2025-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_alter_tbl_table_table_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=30)),
                ('manager_email', models.CharField(max_length=30)),
                ('manager_contact', models.IntegerField()),
                ('manager_password', models.CharField(max_length=30)),
                ('manager_photo', models.FileField(upload_to='Assets/Files/Manager')),
            ],
        ),
    ]
