# Generated by Django 5.1.3 on 2025-02-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_tbl_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_staff',
            name='staff_experience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
