# Generated by Django 5.1.3 on 2024-12-14 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_guestreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestreg_name', models.CharField(max_length=30)),
                ('guestreg_contact', models.CharField(max_length=30)),
                ('guestreg_address', models.CharField(max_length=50)),
                ('guestreg_pass', models.CharField(max_length=30)),
                ('guestreg_email', models.CharField(max_length=30)),
                ('guestreg_photo', models.FileField(upload_to='Assets/Files/User')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
