# Generated by Django 5.1.3 on 2025-02-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_tablebooking',
        ),
    ]
