# Generated by Django 5.1.3 on 2025-02-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_tbl_staff_staff_experience'),
        ('Guest', '0003_tbl_user_user_status'),
        ('User', '0002_delete_tbl_tablebooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tablebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablebokking_end', models.TimeField()),
                ('tablebooking_date', models.DateField(auto_now_add=True)),
                ('tablebooking_status', models.IntegerField(default=0)),
                ('tablebooking_fordate', models.DateField()),
                ('tablebooking_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_table')),
            ],
        ),
    ]
