# Generated by Django 5.1.3 on 2025-02-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_tbl_tablebooking_tbl_tickets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_tickets',
        ),
    ]
