# Generated by Django 5.1.7 on 2025-03-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_tbl_staff_staff_experience'),
        ('User', '0004_delete_tbl_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bookedtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_table')),
                ('tablebooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_tablebooking')),
            ],
        ),
    ]
