# Generated by Django 5.1.3 on 2025-01-04 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0019_alter_tbl_table_table_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(auto_now_add=True)),
                ('schedule_todate', models.DateField(max_length=30)),
                ('schedule_fromtime', models.CharField(max_length=30)),
                ('schedule_totime', models.CharField(max_length=30)),
                ('schedule_work', models.CharField(max_length=50)),
                ('Schedule_work_fromtime', models.CharField(max_length=30)),
                ('Schedule_work_totime', models.CharField(max_length=30)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
            ],
        ),
    ]
