# Generated by Django 5.1.7 on 2025-03-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_tbl_staff_staff_experience'),
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_amount', models.CharField(max_length=30)),
                ('salary_date', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_staff')),
            ],
        ),
    ]
